openapi: 3.0.0
info:
  title: API Turuku
  description: Dokumentasi API untuk aplikasi Turuku
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Server lokal

paths:
  /api/v1/users:
    get:
      summary: Mendapatkan daftar pengguna
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Daftar pengguna berhasil diambil
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
        '401':
          description: Token tidak valid

  /api/v1/register:
    post:
      summary: Mendaftar pengguna baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confPassword:
                  type: string
      responses:
        '201':
          description: Pengguna berhasil terdaftar
        '400':
          description: Permintaan tidak valid

  /api/v1/login:
    post:
      summary: Masuk sebagai pengguna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  userId:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: Email tidak ditemukan
        '400':
          description: Password salah

  /api/v1/token:
    get:
      summary: Mengambil token akses baru menggunakan refresh token
      responses:
        '200':
          description: Token akses berhasil diperbarui
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Token tidak ditemukan

  /api/v1/logout:
    delete:
      summary: Keluar dari sesi pengguna
      responses:
        '200':
          description: Logout berhasil
        '204':
          description: Tidak ada token untuk dihapus

  /api/v1/userdata:
    post:
      summary: Menyimpan data pengguna
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                age:
                  type: integer
                gender:
                  type: string
                chronotype:
                  type: string
      responses:
        '200':
          description: Data pengguna berhasil disimpan
        '401':
          description: Token tidak valid
        '400':
          description: Permintaan tidak valid

    get:
      summary: Mendapatkan data pengguna
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Data pengguna berhasil diambil
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    age:
                      type: integer
                    gender:
                      type: string
                    chronotype:
                      type: string
        '401':
          description: Token tidak valid
  /api/v1/changePassword:
    patch:
      summary: Mengubah kata sandi pengguna
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                  description: Kata sandi saat ini
                newPassword:
                  type: string
                  description: Kata sandi baru
                confNewPassword:
                  type: string
                  description: Konfirmasi kata sandi baru
      responses:
        '200':
          description: Kata sandi berhasil diperbarui
        '400':
          description: Permintaan tidak valid
        '401':
          description: Token tidak valid
        '404':
          description: Pengguna tidak ditemukan

  /api/v1/chronotype:
    post:
      summary: Mengatur chronotype pengguna
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chronotype:
                  type: string
                  description: Chronotype yang ingin diatur
      responses:
        '200':
          description: Chronotype berhasil diperbarui
        '400':
          description: Permintaan tidak valid
        '401':
          description: Token tidak valid

  /api/v1/sleeprecomendation:
    post:
      summary: Mendapatkan rekomendasi tidur berdasarkan data pengguna
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                daily_steps:
                  type: integer
                  description: Jumlah langkah harian
                physical_activity_level:
                  type: integer
                  description: Tingkat aktivitas fisik
                age:
                  type: integer
                  description: Usia pengguna
                gender:
                  type: integer
                  description: Jenis kelamin pengguna (0 untuk perempuan, 1 untuk laki-laki)
                chronotype:
                  type: integer
                  description: Chronotype pengguna
      responses:
        '200':
          description: Rekomendasi tidur berhasil diperoleh
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommended_sleep_duration:
                    type: string
                    description: Durasi tidur yang direkomendasikan
        '400':
          description: Permintaan tidak valid
        '401':
          description: Token tidak valid

  /api/v1/sleeprecommendation:
    get:
      summary: Mendapatkan rekomendasi tidur terakhir untuk pengguna
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Rekomendasi tidur berhasil diambil
          content:
            application/json:
              schema:
                type: object
                properties:
                  sleep_recommendation:
                    type: string
                    description: Rekomendasi tidur terakhir
        '404':
          description: Data rekomendasi tidur tidak ditemukan
        '401':
          description: Token tidak valid
  /api/v1/history:
    post:
      summary: Menyimpan riwayat pengguna
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bedtime:
                  type: string
                  format: time
                  description: Waktu tidur
                wakeuptime:
                  type: string
                  format: time
                  description: Waktu bangun
                physical_activity_level:
                  type: integer
                  description: Tingkat aktivitas fisik
                daily_steps:
                  type: integer
                  description: Jumlah langkah harian
                sleep_recomendation:
                  type: string
                  description: Rekomendasi tidur
      responses:
        '200':
          description: Riwayat berhasil disimpan
        '400':
          description: Permintaan tidak valid
        '401':
          description: Token tidak valid

    get:
      summary: Mendapatkan riwayat pengguna
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Riwayat pengguna berhasil diambil
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID riwayat
                    id_user:
                      type: integer
                      description: ID pengguna
                    bedtime:
                      type: string
                      format: time
                      description: Waktu tidur
                    wakeuptime:
                      type: string
                      format: time
                      description: Waktu bangun
                    physical_activity_level:
                      type: integer
                      description: Tingkat aktivitas fisik
                    daily_steps:
                      type: integer
                      description: Jumlah langkah harian
                    sleep_recomendation:
                      type: string
                      description: Rekomendasi tidur
                    created_at:
                      type: string
                      format: date-time
                      description: Waktu pembuatan riwayat
                    updated_at:
                      type: string
                      format: date-time
                      description: Waktu pembaruan riwayat
        '404':
          description: Data riwayat tidak ditemukan
        '401':
          description: Token tidak valid