openapi: 3.0.3
info:
  title: Turuku RESTful API
  version: 1,0
  contact:
    name: Faiq Radiansyah
    url: https://github.com/Toru45
  description: Keleksi Turuku API APP project capstone bangkit
servers:
  - url: http://localhost:3000/api/v1
components:
  securitySchemes:
    BearerAuth:
      name: jwt-token
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT

paths:
  /users:
    get:
      security:
        - bearerAuth: []
      summary: Mendapatkan informasi pengguna yang sedang login
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Token JWT untuk mengautentikasi pengguna
          schema:
            type: string
      responses:
        '200':
          description: Berhasil mendapatkan informasi pengguna
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
        '404':
          description: Pengguna tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: Terjadi kesalahan pada server
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

  /register:
    post:
      summary: Mendaftar pengguna baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                  format: email
                  required: true
                password:
                  type: string
                  required: true
                confPassword:
                  type: string
                  required: true
      responses:
        '200':
          description: Registrasi berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '400':
          description: Kesalahan validasi input. User harus register dengan minimal 1 angka,1 huruf, 1 symbol dan minimal 8 huruf. serta email harus memiliki '@' dan tidak boleh sudah terdaftar
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: Terjadi kesalahan pada server
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

  /login:
    post:
      summary: Masuk ke akun pengguna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  required: true
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: Login berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          description: Password salah atau email tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '404':
          description: Email tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string


  /logout:
    delete:
      security:
        - bearerAuth: [ ]
      summary: Keluar dari akun pengguna
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Token JWT untuk mengautentikasi pengguna
          schema:
            type: string
      responses:
        '200':
          description: Logout berhasil
        '204':
          description: Tidak ada token untuk dihapus
        '404':
          description: Pengguna tidak ditemukan

  /token:
    get:
      security:
        - bearerAuth: []
      summary: Mendapatkan token baru menggunakan refresh token
      responses:
        '200':
          description: Token berhasil diperbarui
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Refresh token tidak valid atau telah kedaluwarsa
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '500':
          description: Terjadi kesalahan pada server
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string